version: "3"
services:
  api:
    build:
      context: ./
      dockerfile: /home/source/service/docker/app/Dockerfile
    container_name: api
    restart: always
    ports:
      - 3333:3333
    volumes:
      - /home/source/service/:/home/source/service/
      - /path_to_storage:/path_to_storage
      - /home/source/service/node_modules
    links:
      - ws
      - mongodb
      - mongodbrlc1
      - mongodbrlc2
    depends_on:
      - mongodb
      - mongodbrlc1
      - mongodbrlc2
  schedule:
    build:
      context: ./
      dockerfile: /home/source/service/docker/schedule/Dockerfile
    container_name: schedule
    restart: always
    volumes:
      - /home/source/service/:/home/source/service/
      - /path_to_storage:/path_to_storage
      - /home/source/service/node_modules
    links:
      - mongodb
      - mongodbrlc1
      - mongodbrlc2
    depends_on:
      - mongodb
      - mongodbrlc1
      - mongodbrlc2
  ws:
    build:
      context: ./
      dockerfile: /home/source/service/docker/ws/Dockerfile
    container_name: ws
    restart: always
    ports:
      - 3355:3355
    volumes:
      - /home/source/service/:/home/source/service/
      - /path_to_storage:/path_to_storage
      - /home/source/service/node_modules
    links:
      - mongodb
      - mongodbrlc1
      - mongodbrlc2
    depends_on:
      - mongodb
      - mongodbrlc1
      - mongodbrlc2
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - /home/source/service/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /path_to_storage:/path_to_storage
    ports:
      - 80:80
      - 443:443
    links:
      - api
      - ws
    depends_on:
      - api
      - ws
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    command: mongod --replSet rs0 --smallfiles --oplogSize 128 --auth --keyFile /home/source/service/docker/mongodb/keyfile
    volumes:
      - /home/data/mongo/db:/data/db
      - /data/configdb
      - /home/source/service/docker/mongodb/keyfile:/home/source/service/docker/mongodb/keyfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=
      - MONGO_INITDB_DATABASE=db
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=db
    ports:
      - 27117:27017
  mongodbrlc1:
    image: mongo:latest
    container_name: mongodbrlc1
    command: mongod --replSet rs0 --smallfiles --oplogSize 128 --auth --keyFile /home/source/service/docker/mongodb/keyfile
    depends_on:
      - mongodb
    volumes:
      - /data/db
      - /home/source/service/docker/mongodb/keyfile:/home/source/service/docker/mongodb/keyfile
    ports:
      - 27118:27017
  mongodbrlc2:
    image: mongo:latest
    container_name: mongodbrlc2
    command: mongod --replSet rs0 --smallfiles --oplogSize 128 --auth --keyFile /home/source/service/docker/mongodb/keyfile
    depends_on:
      - mongodb
    volumes:
      - /data/db
      - /home/source/service/docker/mongodb/keyfile:/home/source/service/docker/mongodb/keyfile
    ports:
      - 27119:27017

